apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 12ec4562f5901ea6ea050ab0de8ec0cb46e045ee
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 12ec4562f5901ea6ea050ab0de8ec0cb46e045ee
resources:
  - manifests.yaml