apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 0231bb5f26f60a878eb177712a76611b167405c5
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 0231bb5f26f60a878eb177712a76611b167405c5
resources:
  - manifests.yaml