apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-connector-cm
data:
  GIT_REPOSITORY_TYPE: {{ required "Provide a value" .Values.gitRepositoryType}}
  CICD_ORCHESTRATOR_TYPE: {{ required "Provide a value" .Values.ciCdOrchestratorType}}
  GITOPS_OPERATOR_TYPE: {{ required "Provide a value" .Values.gitOpsOperatorType}}
  GITOPS_APP_URL: {{ required "Provide a value" .Values.gitOpsAppURL}}
  
  {{- if eq .Values.gitRepositoryType "AZDO"}}
  AZDO_GITOPS_REPO_NAME: {{ required "Provide a value" .Values.azdoGitOpsRepoName}}
  {{- end }}
  
  {{- if eq .Values.ciCdOrchestratorType "AZDO"}}
  AZDO_PR_REPO_NAME: {{ .Values.azdoPrRepoName}}
  {{- end }}
  
  {{- if or (eq .Values.gitRepositoryType "AZDO") (eq .Values.ciCdOrchestratorType "AZDO")}}
  AZDO_ORG_URL: {{ required "Provide a value" .Values.azdoOrgUrl}}
  {{- end }}
  
  
  {{- if eq .Values.ciCdOrchestratorType "GITHUB"}}
  GITHUB_GITOPS_REPO_NAME: {{ required "Provide a value" .Values.gitHubGitOpsRepoName}}
  {{- end }}

  {{- if eq .Values.gitRepositoryType "GITHUB"}}
  GITHUB_GITOPS_MANIFEST_REPO_NAME: {{ required "Provide a value" .Values.gitHubGitOpsManifestsRepoName}}
  {{- end }}

  {{- if or (eq .Values.gitRepositoryType "GITHUB") (eq .Values.ciCdOrchestratorType "GITHUB")}}
  GITHUB_ORG_URL: {{ required "Provide a value" .Values.gitHubOrgUrl}}
  {{- end }}
